// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace console_games {
	public class Cara_coroa: Game {
		public Cara_coroa (): base() {
		}

		public override void play_game () {
			string moeda;
			Console.WriteLine ("Qual a face que saiu? Cara ou coroa?");
			moeda = Console.ReadLine ();

			if ("cara".Equals (moeda, StringComparison.OrdinalIgnoreCase)) {
				winner = 0;
			} else if ("coroa".Equals (moeda, StringComparison.OrdinalIgnoreCase)) {
				winner = 1;
			}
		}

		protected override string get_msg_player_name (int player_number) {
			string tipo = null;
			string msg = null;
			switch (player_number) {
			case 0:
				tipo = "cara";
				break;
			case 1:
				tipo = "coroa";
				break;
			}

			if (tipo != null) {
				msg = "O jogador será " + tipo;
			}

			return msg;
		}

		public override bool confirmacao_jogador() {
			string r = null;

			Console.WriteLine ("Certeza que " + players[0] + " para cara e " + players[1] + " para coroa? [SN]");
			r = Console.ReadLine ();
			return "s".Equals(r, StringComparison.OrdinalIgnoreCase);
		}
	}
}

