// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace console_games {
	public class Game {
		protected string[] players;
		protected int n_jogadores;
		protected int winner;

		public Game () {
		}

		public string get_winner() {
			return winner < 0? null: players[winner];
		}

		public virtual void play_game() {
			Console.WriteLine ("Well, this is not playable...");
		}

		public virtual void post_game () {
			if (winner >= 0 && winner < n_jogadores) {
				Console.WriteLine ("O vencedor foi: " + players [winner]);
			} else {
				Console.WriteLine ("Não houve vencedores");
			}
		}

		public void prepare_game() {
			winner = -1;
			Console.WriteLine ("Preparando o jogo...");
			n_jogadores = get_n_jogadores();
			players = new string[n_jogadores];

			do {
				for (int i = 0; i < n_jogadores; i++) {
					Console.WriteLine ("Digite o nome do jogador " + (i + 1));
					string msg_player_name = get_msg_player_name(i);

					if (msg_player_name != null) {
						Console.WriteLine(msg_player_name);
					}
					players [i] = Console.ReadLine ();
				}
			} while (!confirmacao_jogador());

			init_game ();
		}

		protected virtual string get_msg_player_name (int player_number) {
			return null;
		}

		protected virtual int get_n_jogadores() {
			return 2;
		}

		protected virtual void init_game() {
		}

		public virtual bool confirmacao_jogador() {
			return true;
		}
	}
}

