// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace console_games {
	public class Par_impar: Game {
		public Par_impar (): base() {
		}

		public override void play_game () {
			int a, b;
			Console.WriteLine ("Qual número " + players[0] + " jogou?");
			a = Convert.ToInt32 (Console.ReadLine ());
			Console.WriteLine ("Qual número " + players[1] + " jogou?");
			b = Convert.ToInt32 (Console.ReadLine ());
			winner = (a + b)% 2;
		}

		protected override string get_msg_player_name (int player_number) {
			string tipo = null;
			string msg = null;
			switch (player_number) {
			case 0:
				tipo = "par";
				break;
			case 1:
				tipo = "impar";
				break;
			}
			
			if (tipo != null) {
				msg = "O jogador será " + tipo;
			}
			
			return msg;
		}

		public override bool confirmacao_jogador() {
			string r = null;
			
			Console.WriteLine ("Certeza que " + players[0] + " para par e " + players[1] + " para impar? [SN]");
			r = Console.ReadLine ();
			return "s".Equals(r, StringComparison.OrdinalIgnoreCase);
		}
	}
}

